# Generated by Django 5.1.7 on 2025-03-14 09:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_name", models.CharField(max_length=28, verbose_name="用户名")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=22, null=True, verbose_name="姓名"
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=22, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation time"
                    ),
                ),
                (
                    "last_modify_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last modify time",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=11, verbose_name="用例编号")),
                (
                    "bug_no",
                    models.IntegerField(blank=True, null=True, verbose_name="缺陷编号"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="用例名称")),
                ("step", models.CharField(max_length=150, verbose_name="步骤")),
                ("expect", models.CharField(max_length=100, verbose_name="期望结果")),
                ("actual", models.CharField(max_length=100, verbose_name="实际结果")),
                ("author", models.CharField(max_length=20, verbose_name="作者")),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[(1, "P0"), (2, "P1"), (3, "P2"), (4, "P3")],
                        default=1,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "未执行"), (2, "通过"), (3, "未通过")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="部门名称")),
            ],
        ),
        migrations.CreateModel(
            name="MemberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=22, null=True, verbose_name="名称"
                    ),
                ),
                (
                    "quantity",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="数量(单位：月)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=28, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "is_delete",
                    models.SmallIntegerField(
                        choices=[(0, "删除"), (1, "正常")],
                        default=1,
                        verbose_name="逻辑删除",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation time"
                    ),
                ),
                (
                    "last_modify_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last modify time",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_name", models.CharField(max_length=28, verbose_name="账号")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=22, null=True, verbose_name="昵称"
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "account",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="授权到期时间"
                    ),
                ),
                (
                    "is_delete",
                    models.SmallIntegerField(
                        choices=[(0, "删除"), (1, "正常")],
                        default=1,
                        verbose_name="逻辑删除",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation time"
                    ),
                ),
                (
                    "last_modify_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last modify time",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                (
                    "account",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="账户余额",
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="入职时间")),
                (
                    "depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bbs.department"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShopManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=28, verbose_name="店铺用户名"),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(1, "拼多多"), (2, "淘宝"), (3, "抖店"), (4, "京东")],
                        verbose_name="绑定店铺",
                    ),
                ),
                (
                    "is_delete",
                    models.SmallIntegerField(
                        choices=[(0, "删除"), (1, "正常")],
                        default=1,
                        verbose_name="逻辑删除",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation time"
                    ),
                ),
                (
                    "last_modify_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last modify time",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.usermanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="messagesLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_user_id",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="店铺用户ID"
                    ),
                ),
                (
                    "receive_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="接受消息内容"
                    ),
                ),
                (
                    "send_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="发送消息内容"
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation time"
                    ),
                ),
                (
                    "last_modify_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last modify time",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.shopmanager",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.usermanager",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="订单号"
                    ),
                ),
                (
                    "pay_type",
                    models.SmallIntegerField(
                        choices=[(1, "支付宝"), (2, "微信")], verbose_name="支付方式"
                    ),
                ),
                (
                    "is_delete",
                    models.SmallIntegerField(
                        choices=[(0, "删除"), (1, "正常")],
                        default=1,
                        verbose_name="逻辑删除",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="creation time"
                    ),
                ),
                (
                    "last_modify_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="last modify time",
                    ),
                ),
                (
                    "memer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.membermodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bbs.usermanager",
                    ),
                ),
            ],
        ),
    ]
