# Generated by Django 5.1.7 on 2025-03-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=11, verbose_name="用例编号")),
                (
                    "bug_no",
                    models.IntegerField(blank=True, null=True, verbose_name="缺陷编号"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="用例名称")),
                ("step", models.CharField(max_length=150, verbose_name="步骤")),
                ("expect", models.CharField(max_length=100, verbose_name="期望结果")),
                ("actual", models.CharField(max_length=100, verbose_name="实际结果")),
                ("author", models.CharField(max_length=20, verbose_name="作者")),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[(1, "P0"), (2, "P1"), (3, "P2"), (4, "P3")],
                        default=1,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "未执行"), (2, "通过"), (3, "未通过")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
        ),
    ]
