"""
Django settings for customer project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f^grxd30qj3jh!7g3@#5_rnbx)bl2r48%4dpcll(a!#+y-#p9&"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bbs.apps.BbsConfig"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "bbs.middleware.auth.AuthMiddleware"
]

ROOT_URLCONF = "customer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')]   # 保证路径配置正确
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "customer.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangoblog',
        'USER': 'root',
        'PASSWORD': 'Heng1991!@#',
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "bbs/static")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ALI_PAY_APP_ID="2021005129640221"
ALI_PAY_DEBUG=True
ALI_PAY_CALL_BACK_URL="http://127.0.0.1:8000/index/pay_result/"
ALI_PAY_GATEWAY_URL="https://openapi.alipay.com/gateway.do?"

ALIPAY_PUBLIC_KEY_STRING = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh/onLcsg16TmJb3fdSFqtE2y3eQLZjyvT1v1y98YaOpDHaK7CHiCaVQ6H1HmsBKlG6lvF3kBaRjXakVLqouKy8oW94CLDVZoHMo1dMF1uNlLDeReo1xhit/I6Sk77+LQ6Rp0kpu7dAByJb7wcmJZ4Gme7rp2EkvwY58FR2V51C7GHU6lKPB16K15U8M3R9Xwc8slxuzoGp/h4KoeWxbFGl/nIiEpwFzZHNOTNAYOO3pBDcv9++OCraD015qmVBlAZ1GcLkUkYpeFMJwygnqA8NzM9hEoMQYaTe4ccPG+NvWb6mOFCJpGzEBcXpaJxz7i1BHnDq7MeUCuPPaFHMvVxwIDAQAB
-----END PUBLIC KEY-----"""
ALIPAY_PRIVATE_KEY_STRING = """-----BEGIN RSA PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXgVCzNBL6/F4XCHVWjBKNIq0GNfKGfJNOCWv/vkU8lVcj7xfZUcS1l3WGRK55lDLDLax3Vmh5853QxUlOyc4tRQGLuH5RvTeksKWse7Yt37Cpc6bAvs1rAf4rLwox51vBoYWtx0rydJYzw6QhWyaqo1uWfSOQIiPW+dnnIsbxZIIHaYg4OKGl74id3V850yQ7e3JnJZ1NXX1XWxtmBVX8vlt/MXhUNa8JApqS6Qh/qeu4WdAH86EjHsX7hv7s7+ksKJUQL9wwXTWN9cX7iGEqj0KhBtlSWY6vxEp02O5gLmETgAldNWzka8DvDoLsmKzOqsNhJ4NvuF4BO9cD+sJVAgMBAAECggEAYnsw4sPQTKwZX1M5M/TM4XxQL39ltjmlo0rA9N0BjN7+NGilsGUijI2LYnFufhbQX8s2fk6Zbel7XBVcG8ozExLu0ufbqgTbMcKb40ehiDMp6zXzpS9MdjMx8JANi6Kbls/2Y+SoBkZrAXrNPYUHFYGTcCD9qHdBg5MoFe0ZluOtccXhZfcvz99Vn8n9vVa7l9dS34qIO74vXO4pftUvM2M5zmKDesNVXZEcknxeI/+YNZBu6AKTADU47HZO0/98H/rzJzG3mxGAlcndZiv6iQ+1frZnhQKt2za0BD/eBj/mrG9dPp/m2W6uWDANJscre/Yqc22gW39U97C1/zSR3QKBgQD2RgaWOr/A/uGge4ZhONsH70TUGomZI7BIroNRpXbTX27t+HaifLZXSeYm+2EB/oWQR8vTFMHWy+seUeknqM29KVE4DdLbDI2BacY2CiOnvnrbkrVa1pgmNZTUzPCemryReAXFmbpKnm+XIV9vm5EGjeFf3ilPsq+0TNkRdyG35wKBgQDgBDPPlhbccB2ukC7jwB78n3qTieTn5IVSCZ4LK0VdqD1FQIgy7Pik+AKcMp2jOfdZ1NDLTwmFdItwvJdBrQe7eXfHqxLYSp4jN+bg0GDc+PAYU5Uhn9n3nuko9NBH/eDSnzISeglXNRtj+zk5IAxBJdaXdeWg+qQVsrr0QaW8YwKBgA9OMNCbXBl5fbpEkwhtyScIFsX71DthPW528hBb8TOXxcQiYfUdPRPVsukPTGscT161J5S5wIZB7B3ZR11An3C3JaYPLeCROiYl1by8CpU9QFNvHbhEh/Yv9Ez5Y6bnxPphdDJgqHREvnitCUpdZ7j5jl0v6G9ckpDpCcCNH9pXAoGBAMHZ4RvZvZ60RnswueLL9gSV3PSfdz5UOipruB/iKfyKAbtTxIiNF/1pwJh6FH+TQcCysJu+oXajC6dbC2kB2pcY3dYi7APPTlkbnuccazXNFbd3XK3kLjJhiVKvxy0FPPAGYsYqZLracgFq/HG6keAuZixbEYLkYemE6NNFm64RAoGBALpEg+I5NEYQX45eLjsNh6RzIJdBADKm4dYKNXoPOXfkdiH75tVAokB5cXPZDSXnHTOBch81/6exc4JRn+Tsy7JpEpjLEMfjWEamb4EpXp2SIagCHvOFqaTjknnbhsYFOKzSjGXATp+D/jC0Ihq1uJMoqwR2uKeEiMY01MEjgExP
-----END RSA PRIVATE KEY-----"""

FILE_DOWN_PATH = os.path.dirname(os.path.abspath(__file__))